In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [5]:
import numpy as np
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [11]:
import numpy as np
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
import numpy as np
np.ones(3)

array([1., 1., 1.])

In [13]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])